#ifndef __POSBOX__
#define __POSBOX__

typedef enum POSBOX_POS_ {
	POS_TOPLEFT,
	POS_TOPCENTER,
	POS_TOPRIGHT,
	POS_MIDDLELEFT,
	POS_MIDDLECENTER,
	POS_MIDDLERIGHT,
	POS_BOTTOMLEFT,
	POS_BOTTOMCENTER,
	POS_BOTTOMRIGHT
} POSBOX_POS;

/* ×¢²áPosBox²¿¼þ */
void Register_PosBox(void);

#endif